---
title: "读书笔记"
author: "samsen/陈森盛"
date: "01/01/2015"
output: html_document
---

- - -  

##互联网企业的战略管理##########

\   **三种基本战略类型**

>+  总成本领先  
>+  差异化战略  
>+  聚焦战略  
  
  
\   **淘宝采取的策略**

>+  免费；实名认证（ebay收费）  
>+  推出支付宝  
>+  推出阿里旺旺（ebay邮件沟通）
  
\   **互联网战略思考**

>-  最大特点："客户对客户"  
>-  听到客户发出的声音  

- - -


##网上拍卖交易机制的有效性研究_淘宝网面板数据的证据_吴德胜###  

\   **卖家刷信用**  
    Ebay和淘宝为完善评价系统推出：  
    
>+  店铺动态评分  
>+  卖家服务质量

\  **淘宝的购物搜索情况**  
    淘宝网统计：
    
>1.  `搜索首页的浏览量占据淘宝网浏览总量的70%`（不知道包不包扩一淘等其他的）   
>2.  `首页搜索中的72%的流量贡献给了前20个店铺`（以行为单位，差不多下拉一会的数量）

\  **淘宝网的搜索排序规则**  
    
    主要依据商品下架时间，由提供价格和信用度排序 -> 销量排序 -> 综合信用度、销量、价格排序（2011年7月）  
    
\  **流量数据的时效性概念**  

    考虑到成交量是过去单位时间内的值，而当前研究节点上的评价指标在时间节点上必然带来误差，考虑用面板数据
    
###信任保障机制和搜索机制的介绍#############################

1. 信用评价系统 
  主要分为五大块：  

>+  基本信用评价指标  
>
>>  `信用度`  
    `好评`  
    `实物商品交易`
>
>+  最近信用评价指标  
>
>>  `一周`  
    `一月`  
    `半年`  
    `一年`  
>
>+  卖家服务质量  
>
>>  `违规行为`  
    `退款纠纷`  
    `投诉纠纷`  
    `处罚情况`
>
>+  店铺动态评分
>
>>  `宝贝与描述相符程度`  
    `卖家的服务态度`  
    `卖家发货速度`
>
>+  具体评价内容或来自买家的评价  
>
>>  `具体的评价内容`  
    `评价者的信息`
    
\  **支付机制**  

    第三方支付；第三方托管；货到付款；信用卡支付  
\  **消费者保障服务**  

    七天退换；假一赔三；正品保障；30天维修

\  **旺铺**  

    普通店铺；淘宝旺铺（淘宝提供的一种增值服务）
    
\  **购物搜索**  

    关键词搜索；分类搜索；分类下的关键词搜索
    信息瀑布理论（Information Cascade）：购买决策会暴露消费者掌握的私有信息；排序使消费者模仿他人，从“他人”得到信息节约搜索成本  
    
\  **一淘成立**  
    
    提供全互联网购物商品价格等信息  
    
###对于作者研究方法的评价###########################

\  **数据搜集方法**  

    作者选取的是U盘的数据，从U盘的结果直接推广到整个淘宝，是否可行？  
      
    与搜索结果相对应的还有卖家对于商品的描述信息，作者通过输入不同的搜索关键词获得搜索结果的是否如何考虑这点？
    
    






